---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: corecraft
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.32.6-rc1-k3s1
kubeAPI:
  hostPort: "6550"
ports:
  - port: 9080:80
    nodeFilters:
      - loadbalancer
  - port: 9443:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: corecraft-registry
    hostPort: "12345"
  config: |
    mirrors:
      "corecraft-registry:5000":
        endpoint:
          - http://corecraft-registry:5000
options:
  k3d:
    wait: true
    timeout: 6m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
    nodeLabels: []