---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: corecraft
servers: 1
agents: 1
image: docker.io/rancher/k3s:v1.32.6-rc1-k3s1
kubeAPI:
  hostPort: "6550"
# ports:
#   - port: 80:80
#     nodeFilters:
#       - server:*
#   - port: 443:443
#     nodeFilters:
#       - server:*
registries:
  create:
    name: corecraft-registry
    hostPort: "1234"
  config: |
    mirrors:
      "corecraft-registry:5000":
        endpoint:
          - http://corecraft-registry:5000
options:
  k3d:
    wait: true
    timeout: 6m0s
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
    nodeLabels: []